//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladorTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbproducto
    {
        public int idp { get; set; }
        public string nombre { get; set; }
        public decimal costo { get; set; }
        public decimal precio { get; set; }
        public int preferencia { get; set; }
        public int idcate { get; set; }
    
        public virtual tbcategoria tbcategoria { get; set; }
    }
}
